[workspace]
resolver = "2"
members = ["nats_client", "nats_codec", "nats_server"]

[workspace.dependencies]
tokio = { version = "1.38.0", default-features = false }
tokio-stream = { version = "0.1.15" } 
tokio-util = { version = "0.7.11", default-features = false }
